# Workflow name
name: custom-action-demo

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main

# Jobs defined in the workflow
jobs:
  custom-action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependency
        run: npm i @actions/core
          
      - name: Run Custom action
        uses: anubhavkumar1705/business-greetings-action@main
